### ISSUE TITLE
2020年学习日记

### ISSUE THREAD

**Issue by youngjuning** [youngjuning/youngjuning#2]

**Comment by youngjuning** [comment]
## 2020年7月16日

- [ ] 看vue文档复习vue基础语法
- [ ] 看一篇 React Hooks 的文章
  - [ ][终于搞懂 React Hooks了！！！！！](https://juejin.im/post/5e53d9116fb9a07c9070da44)
- [ ] 编写 Lodash 源码解析文章
- [ ] 完成掘金年中总结的征文

**Comment by youngjuning** [comment]
2020年7月17日

- [ ] 整理 github issues

**Comment by youngjuning** [comment]
## 2020年7月20日

- [ ] 看一篇 React Hooks 的文章
  - [ ] [终于搞懂 React Hooks了！！！！！](https://juejin.im/post/5e53d9116fb9a07c9070da44)
- [ ] 编写 Lodash 源码解析文章

**Comment by youngjuning** [comment]
## 2020年7月21日

恭喜自己，完成了一个小目标：

![](https://i.loli.net/2020/07/21/hkr7IvQHYRMTP3o.png)

- [ ] 看一篇 React Hooks 的文章
  - [ ] [终于搞懂 React Hooks了！！！！！](https://juejin.im/post/5e53d9116fb9a07c9070da44)
- [ ] 编写 Lodash 源码解析文章

**Comment by youngjuning** [comment]
## 2020年7月21日

 - [  ] 编写 Lodash 源码解析文章
-  [  ] 阅读React官方文档

**Comment by youngjuning** [comment]
## 2020年7月23日

> 暴雨未至

- [ ]  编写 Lodash 源码解析文章
- [ ]  阅读React官方文档
- [ ] ESLint 规则插件
- [ ] 一道LeetCode算法题

> 早上没能早起，晚上带我家豆豆（一只小体比熊）剃胎毛啦，编写 Lodash 源码解析的文章拖了许久，深感愧疚

**Comment by youngjuning** [comment]
## 2020年7月24日

- [ ]  编写 Lodash 源码解析文章
- [ ]  阅读React官方文档
- [ ] 一道LeetCode算法题

## 阅读的文章

- [ ] [useEffect 完整指南](https://overreacted.io/zh-hans/a-complete-guide-to-useeffect/)
- [ ] [immutablejs 是如何优化我们的代码的？](https://mp.weixin.qq.com/s/lCiN8XVlzhLPoMnvK3IjVw)

**Comment by youngjuning** [comment]
## 2020年7月24日

- [ ]  编写 Lodash 源码解析文章
- [x]  阅读React官方文档
- [ ] 一道LeetCode算法题

## 阅读的文章

- [ ] [捕获 React 异常](https://juejin.im/post/5e1d1c23e51d4501fe5bc62d)
- [ ] [useEffect 完整指南](https://overreacted.io/zh-hans/a-complete-guide-to-useeffect/)
<img src="https://i.loli.net/2020/07/25/A3lnkRXWfg27zMZ.png"  width="500">

**Comment by youngjuning** [comment]
## 2020年7月24日

### TODO

- [ ]  编写 Lodash 源码解析文章
- [ ]  阅读React官方文档
- [ ] 一道LeetCode算法题
- [x] 入门deno并写掘金征文

### 打卡

<img src=https://user-images.githubusercontent.com/13204332/88530504-0e98e780-d034-11ea-8f74-a8bf8cff8572.png"  width="300">

**Comment by youngjuning** [comment]
## 2020年7月28日

### TODO

- [x] 阅读React文档

### 打卡

<img src="https://i.loli.net/2020/07/29/hl1KEZVauF6PLRI.png" width="300">

**Comment by youngjuning** [comment]
### 阅读

- [Using Deno to Build a HTTP Server](https://www.youtube.com/watch?v=dp8eedoRpyo&t=504s)
- [了不起的 Deno 入门与实战](https://juejin.im/post/5ec24dea6fb9a04388076fba)

**Comment by youngjuning** [comment]
## 2020年7月30日

### TODO

- [ ] 阅读React官方文档
- [ ] 完成Lodash源码解析文章
- [ ] Fusion 库熟悉

### 阅读

- [ ] [了不起的 Deno 入门与实战](https://juejin.im/post/5ec24dea6fb9a04388076fba)
- [ ] [Deno快速入门指南](https://www.bilibili.com/video/BV1A5411x7bg)
- [ ] [Write a small API using Deno](https://dev.to/kryz/write-a-small-api-using-deno-1cl0)
- [ ] [5 Ways to Build a HTTP Server With Deno](https://medium.com/@tomanagle/5-ways-to-build-a-http-server-with-deno-3169389118aa)
- [ ] [Deno + mongodb 实战踩坑记](https://juejin.im/post/5ec650b5e51d45786672a4e1)

### 打卡

**Comment by youngjuning** [comment]
## 2020年7月31日

### TODO

- [ ] 完成Deno HTTP Server 文章
  - [ ] 看相关博客、mongoDB入门、oak入门、书籍列表管理API
- [ ] Fusion 库熟悉
- [ ] 翻译 [Creating a server with deno and mongo](https://dev.to/slimhmidi/create-a-server-with-deno-and-mongo-206l)

### 阅读

- [ ] [了不起的 Deno 入门与实战](https://juejin.im/post/5ec24dea6fb9a04388076fba)
- [ ] [Deno快速入门指南](https://www.bilibili.com/video/BV1A5411x7bg)
- [ ] [Write a small API using Deno](https://dev.to/kryz/write-a-small-api-using-deno-1cl0)
- [ ] [5 Ways to Build a HTTP Server With Deno](https://medium.com/@tomanagle/5-ways-to-build-a-http-server-with-deno-3169389118aa)
- [ ] [Deno + mongodb 实战踩坑记](https://juejin.im/post/5ec650b5e51d45786672a4e1)
- [ ] [Creating a CRUD API in Deno with Oak and MongoDB](https://medium.com/javascript-in-plain-english/deno-oak-mongo-3d29542333fd)
- [ ] [Creating a server with deno and mongo](https://dev.to/slimhmidi/create-a-server-with-deno-and-mongo-206l)
- [ ] [【译】Deno + MongoDB 构建 CRUD API](https://mp.weixin.qq.com/s/9lgdrAXA72__i2lkzj2GNA)

### 打卡

<img src="https://i.loli.net/2020/07/30/EvSBCVXKqhc1LRN.png" width="300">

**Comment by youngjuning** [comment]
## 翻译计划

- [oakserver/oak](https://github.com/oakserver/oak) README

**Comment by youngjuning** [comment]
## 2020年8月5日

> 早起失败

### PLAN

- [ ] 编写 dynoak 插件，动态扫描 oak controller 的插件

**Comment by youngjuning** [comment]
## 2020年8月6日

> 早起失败

### PLAN

- [ ] 《CSS揭秘》之半透明边框
- [ ] Lodash 源码解析之object今天必须完成

### 打卡

<img src="https://i.loli.net/2020/08/06/GAguTNBSVPcnsfa.png" width="300">

**Comment by youngjuning** [comment]
## 2020年8月7日

> 前一晚看 CSS揭秘 两点睡的，早起失败

### PLAN

- [ ] 《CSS揭秘》两节
- [ ] 完成《GitHub REST API 简易教程》
- [ ] 完成《从零开发一款deno插件并发布》

### 打卡

<img src="https://i.loli.net/2020/08/06/GAguTNBSVPcnsfa.png" width="300">
